version: '2'
services:
  recruitment:
    image: recruitment
    container_name: recruitment
    restart: unless-stopped
    network_mode: host
    volumes:
      - "${PWD}/logs:/app/logs"
      - "/var/www/html/nps/prison_cms_files:/var/www/html/nps/prison_cms_files"